//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyanCodeChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseId { get; set; }
        public int CustomerId { get; set; }
        public string SKU { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.DateTime> PurchaceDate { get; set; }
    }
}
